- hosts: all
  vars_prompt:
       - name: dvd_dir
         private: no
         prompt: "Enter dvd mount point: "


  tasks:
  - file:
      state: directory
      path: "/{{dvd_dir}}"

  - mount:
      src: "/dev/cdrom"
      path: "/{{dvd_dir}}"
      state: mounted
      fstype: "iso9660"

  - yum_repository:
      baseurl: "/{{dvd_dir}}/AppStream"
      name: "mydvd1"
      description: "my AppStream Packages of DVD"
      gpgcheck: no

  - yum_repository: 
      baseurl: "/{{dvd_dir}}/BaseOS"
      name: "mydvd2"
      description: "my BaseOS Packges of DVD"
      gpgcheck: no
  
  - package:
      name: "httpd"
      state: present
 
  - file:
      state: directory
      path: "/var/www/TD"


  - copy: 
      src: "TD.conf"
      dest: "/etc/httpd/conf.d/Td.conf"
      notify: Web service start 

  - copy:
      src: "web.html"
      dest: "/var/www/TD/web.html"
      notify: Web service start

  - firewalld:
      port: "8080/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  handlers:
  - name: Web service start
    service:
      name: "httpd"
      state: restarted
      enabled: yes
